name: Test CI/CD

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install -r requirements.txt

      - name: Run test
        run: pytest test_calculate/ -v